<?php

namespace App\Service;

use App\Entity\Attachment;
use App\Entity\ContactSubmission;
use App\Exception\SpamDetectedException;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;
use Symfony\Component\Mailer\Transport\TransportInterface;
use Symfony\Component\Mime\Address;
use Symfony\Component\Mime\Email;
use Symfony\Component\Mime\Part\DataPart;
use Symfony\Component\Mime\Part\File;
use Symfony\Component\Uid\Uuid;

class ContactFormService
{
    const SPAM_DETECTION_PROMPT = "You are an AI assistant specialized in spam detection
    for a French non-profit association called NîmesCricketClub, which promotes the development of cricket in Nîmes, France.
    Your task is to analyze the content of an email and determine if it is genuine or spam.
    Reply `true` if the email is real (genuine), or `false` if it is spam. Emails may be in French or English.
    If the email relates to sports, always reply `true`, even if it appears automated or generated by a bot.
    Do not include explanations, punctuation, or any additional words—only respond with `true` or `false`.";

    public function __construct(
        #[Autowire(param: 'attachments_path')] private readonly string $attachmentsPath,
        private readonly LLMService                                    $llmService,
        private readonly Filesystem                                    $filesystem,
        private readonly EntityManagerInterface                        $entityManager,
        private readonly TransportInterface                            $mailer
    )
    {
    }

    /**
     * @throws TransportExceptionInterface
     * @throws SpamDetectedException
     */
    public function handleFormSubmission(FormInterface $form, ContactSubmission $contactSubmission): void
    {
        if ($this->detectSpam($contactSubmission)) throw new SpamDetectedException();

        foreach ($form->get('attachments')->getData() as $file) {
            $extension = $file->getClientOriginalExtension();
            $path = Uuid::v4()->toRfc4122() . '.' . $extension;
            $fullPath = $this->attachmentsPath . '/' . $path;
            $this->filesystem->dumpFile($fullPath, $file->getContent());

            $attachment = new Attachment();
            $attachment->setName($file->getClientOriginalName())->setPath($path)->setIsPrivate(true);
            $contactSubmission->addAttachment($attachment);
            $this->entityManager->persist($attachment);
        }

        $email = (new Email());

        $email
            ->from(new Address('contact@nimescricketclub.fr', $contactSubmission->getName()))
            ->subject('Message de ' . $contactSubmission->getName() . ' via le formulaire de contact')
            ->to('contact@nimescricketclub.fr')
            ->text('Email: ' . $contactSubmission->getEmail() . "\n\n" . $contactSubmission->getContent());

        foreach ($contactSubmission->getAttachments() as $attachment) {
            $path = $this->attachmentsPath . '/' . $attachment->getPath();
            $email->addPart(new DataPart(new File($path), $attachment->getName()));
        }

        try {
            $this->mailer->send($email);
            $this->entityManager->persist($contactSubmission);
            $this->entityManager->flush();
        } catch (TransportExceptionInterface $e) {
            foreach ($contactSubmission->getAttachments() as $attachment) {
                $path = $this->attachmentsPath . '/' . $attachment->getPath();
                $this->filesystem->remove($path);
            }
            throw $e;
        }
    }

    private function detectSpam(ContactSubmission $contactSubmission): bool
    {
        $query = "Email: " . $contactSubmission->getEmail() . "\n";
        $query .= "Name: " . $contactSubmission->getName() . "\n";
        $query .= $contactSubmission->getContent();
        $result = $this->llmService->query(self::SPAM_DETECTION_PROMPT, $query);
        return str_contains($result, "false");
    }
}
