<?php

namespace App\Service;

use App\Entity\Attachment;
use App\Entity\ContactSubmission;
use App\Exception\SpamDetectedException;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Uid\Uuid;

class ContactFormService
{
    const SPAM_DETECTION_PROMPT = "You are an AI assistant specialized in spam detection
    for a French non-profit association called NîmesCricketClub, which promotes the development of cricket in Nîmes, France.
    Your task is to analyze the content of an email and determine if it is genuine or spam.
    Reply `true` if the email is real (genuine), or `false` if it is spam. Emails may be in French or English.
    If the email relates to sports, always reply `true`, even if it appears automated or generated by a bot.
    Do not include explanations, punctuation, or any additional words—only respond with `true` or `false`.";

    public function __construct(
        private readonly string                 $attachmentsPath,
        private readonly LLMService             $llmService,
        private readonly Filesystem             $filesystem,
        private readonly EntityManagerInterface $entityManager,
        private readonly MailService            $mailService
    )
    {
    }

    /**
     * @throws SpamDetectedException
     */
    public function handleFormSubmission(FormInterface $form, ContactSubmission $contactSubmission): void
    {
        if ($this->detectSpam($contactSubmission)) throw new SpamDetectedException();

        $attachments = [];
        foreach ($form->get('attachments')->getData() as $file) {
            $extension = $file->getClientOriginalExtension();
            $path = Uuid::v4()->toRfc4122() . '.' . $extension;
            $fullPath = $this->attachmentsPath . '/' . $path;
            $this->filesystem->dumpFile($fullPath, $file->getContent());

            $attachment = new Attachment();
            $attachment->setName($file->getClientOriginalName())->setPath($path)->setIsPrivate(true);
            $contactSubmission->addAttachment($attachment);
            $this->entityManager->persist($attachment);

            $attachments[] = [
                'name' => $attachment->getName(),
                'type' => $file->getMimeType(),
                'content' => base64_encode(file_get_contents($fullPath)),
            ];
        }

        $response = $this->mailService->sendMail([
            "recipients" => [['email' => "contact@nimescricketclub.fr"]],
            "body" => [
                "html" => sprintf(
                    "<p>Email: <a href='mailto:%s'>%s</a></p><br><p>%s</p>",
                    $contactSubmission->getEmail(),
                    $contactSubmission->getEmail(),
                    $contactSubmission->getContent()
                ),
            ],
            "subject" => "Message de " . $contactSubmission->getName() . " via le formulaire de contact",
            "from_name" => $contactSubmission->getName(),
            "attachments" => $attachments
        ]);

        if ($response->getStatusCode() === 200) {
            $this->entityManager->persist($contactSubmission);
            $this->entityManager->flush();
        } else {
            foreach ($contactSubmission->getAttachments() as $attachment) {
                $path = $this->attachmentsPath . '/' . $attachment->getPath();
                $this->filesystem->remove($path);
            }
            throw new Exception("Erreur lors de l'envoi du message: " . $response->getStatusCode());
        }
    }

    private function detectSpam(ContactSubmission $contactSubmission): bool
    {
        $query = "Email: " . $contactSubmission->getEmail() . "\n";
        $query .= "Name: " . $contactSubmission->getName() . "\n";
        $query .= $contactSubmission->getContent();
        $result = $this->llmService->query(self::SPAM_DETECTION_PROMPT, $query);
        return str_contains($result, "false");
    }
}
